POST http://localhost:4000/v1/authenticate
Content-Type: application/json

{
	"username":"admin",
	"password":"admin@123"
}

###
GET http://localhost:4000/v1/all-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjJlNzNhMjg2NDQxNGUzODEwYThkNzciLCJpZCI6IjVmMmU3M2EyODY0NDE0ZTM4MTBhOGQ3NyIsImlhdCI6MTU5Njk2NDg0MCwiZXhwIjoxNTk2OTY0OTAwfQ.WfUjVX1mgos_SPe83Y3H9I7W-IYJWjy-zBHDiJ_VVPE